### ISSUE TITLE
[BUG] Settings aren't saving at all.

### ISSUE THREAD

**Issue by asdexter** [p4535992/MountUp#1]
**Module Version:** 
v3.2.0

**Describe the bug**
Setting won't save. I change anything, press save, reopen, and the defaults are there.

**To Reproduce**
Attempt to change any setting

**Foundry Version:** 
0.8.9

**Game System:** 
PF1E 0.79.7

**Comment by rafaelfernandesnet** [comment]
Confirmed, the settings are not saving or changing the behavior.
Like: 

- Chat is always being triggered.
- Rider is always aligned to the top left, etc.

Even though some times when you hit save it changes the checkbox, that does not interfere with the in-game module behavior.

**Comment by p4535992** [comment]
Sorry for the trouble i made a patch , try out 3.2.1 and let me know
