### ISSUE TITLE
[BUG] Most Settings Not Respected

### ISSUE THREAD

**Issue by Hydrall** [p4535992/MountUp#2]
### Environment Details

* Foundry VTT Version: 0.8.9
* Operating System: [Windows, MacOS, Linux (which distro)]
* How Are You Using Foundry: Electron
* Which Game System: dnd5e
* Modules Enabled?: [yes, no] no

### Issue Description

When mounting a token, it posts two messages to chat - one of which is blank and from the GM, the other of which is by the currently selected token. It does not respect the settings, either; it always says "I mount this {name}", when mounting, and "get off {name}!" when dismounting.

My settings have different messages set, and more pertinently I have the "send messages to chat" option completely disabled.

Riders also cannot move on the mount even though NoLock is selected, and so on and so forth.

Strangely, a few settings do work: Changing the button position, icon, and so on all work properly, though are reset to the default the next time I open the settings form.

![image](https://user-images.githubusercontent.com/14931056/139508485-3bbfef72-a8ce-4dc7-9ba4-c0c95378c9d4.png)

**Comment by p4535992** [comment]
Sorry for the trouble i made a patch , try out 3.2.1 and let me know

**Comment by Hydrall** [comment]
I'm still seeing messages whenever I mount or dismount - the blank messages noted before. Also, the position of the mount icon is not saving properly either.
