### ISSUE TITLE
MountUp! not recognised in game

### ISSUE THREAD

**Issue by KJTailor** [p4535992/MountUp#3]
* Foundry VTT Version: 0.89
* Operating System: [Windows, MacOS, Linux (which distro)]
* How Are You Using Foundry: ForgeVTT
* Which Game System: DnD5e 1.5.3

### Issue Description

Hi,
I was trying to make use of the Mount Up! module, but it seems not to be active in my game? I checked in the foundry setup and it was installed correctly and up to date. However, when I actually load the game (details above), it would not appear in the module settings, nor in module management .
Could this be an issue with the most recent 5e version?

Cheers

**Comment by p4535992** [comment]
Sorry for the trouble i made a patch , try out 3.2.1 and let me know, make sure is not the "old" mount up module make sure the version is "3.2.1".

**Comment by KJTailor** [comment]
All good, no trouble at all.
After updating to 3.2.1 it works like a charm. Thank you so much for the effort and quick troubleshooting!
