### ISSUE TITLE
[BUG] MountUp's action button nonfunctional & doesn't render

### ISSUE THREAD

**Issue by bennyty** [p4535992/MountUp#4]
**Module Version:** 3.2.1

**Describe the bug**
The mount up horse icon doesn't appear. Instead an empty box (with correct tooltip) shows. The button does nothing when clicked. No errors in the console.

**To Reproduce**
1. Empty world with the PF2e Game System
2. Drag out two actors
3. Right click on one
4. No horse icon, button is unresponsive.

**Screenshots**
![2021-11-19 14_26_54-Foundry Virtual Tabletop • A Standalone Virtual Tabletop Application](https://user-images.githubusercontent.com/592150/142682579-188e2265-6787-4a0f-8c3c-6dd9f9b68d5d.png)

**Browser:**
 - Chrome Version 96.0.4664.45 (Official Build) (64-bit)

**Foundry Version:** 
- Foundry 0.8.9

**Game System:**
 - PF2e Version 2.18.3.8782

**Additional context**
There was some chatter about this a week or so ago (when the 3.2.1 version was released) on Discord:
https://discord.com/channels/170995199584108546/722566083499786352/908139240699867168

I posted a couple minutes ago about it as well in the same channel, just FYSA.
https://discord.com/channels/170995199584108546/722566083499786352/911337232370126909

**Comment by bennyty** [comment]
I poked around at this some more. If you go into the MountUp settings and change the icon to a different icon, the attaching works. Settings still don't seem to save correctly (same symptoms as #1).

**Comment by Davidomcg** [comment]
Im having the exact same problem. will this be fixed soon?
