### ISSUE TITLE
Cannot Dismount, Rider Alignment Settings not Respected

### ISSUE THREAD

**Issue by 9Volt1** [p4535992/MountUp#9]
* Foundry VTT Version: 9.255
* Operating System: Windows
* How Are You Using Foundry: Chrome through Foundry Server
* Which Game System: DnD 5e
* Modules Enabled?: Mount Up 3.2.15, Libwrapper 1.12.4, Token Attacher 4.4.5, Token-z 6.3, all other modules disabled for troubleshooting purposes

When mounting, rider alignment settings are not respected.  Once mounted, there is not a dismount button, only the mount button which does not trigger a dismount.  Token attacher does not separate the tokens either.  Refreshing the page causes a dismount whether I've tried to dismount or not.

**Comment by p4535992** [comment]
Seem to work as inteded, any error on the webconsole ?

**Comment by 9Volt1** [comment]
> Seem to work as inteded, any error on the webconsole ?

Uncaught (in promise) TypeError: parent is undefined
[Detected 1 package: foundryvtt-mountup]
    isAncestor mountManager.js:610
    mountUpHud mountManager.js:40
    addMountButton mountHud.js:58
    jQuery 8
    addMountButton mountHud.js:57
    renderMountHud mountHud.js:31
    readyHooks module.js:66
    _call foundry.js:294
    call foundry.js:279
    _render foundry.js:3119
    _render foundry.js:52596
    render foundry.js:3023
    bind foundry.js:52571
    bind foundry.js:55058
    _onClickRight foundry.js:21910
    callback foundry.js:24202
    _handleClickRight foundry.js:24454
    _handleRightDown foundry.js:24434
    emit index.js:181
    dispatchEvent interaction.min.js:8
    processPointerDown interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    findHit interaction.min.js:8
    processInteractive interaction.min.js:8
    onPointerDown interaction.min.js:8

**Comment by 9Volt1** [comment]
No Errors popping up. Sorry.

Been experimenting more and can clarify:
When mounting, I have to move the mount token before closing the HUD for the mount to take effect.  Dismounting is the opposite; I have to close the HUD before moving for it to take effect.

As previously mentioned, not respecting alignment settings and unmounts when the page is refreshed.

Much appreciation to you for time spent benefitting others

**Comment by 9Volt1** [comment]
Sorry, need to clarify the behavior:  What I thought was mounting was just the fact that both tokens were still selected.  Silly oversight; I live in Colorado. ;)  So the behavior is simply that the mount button is not responding.

Very occasionally, as in twice in about half an hour of fiddling with the mod, the following shows on the console:

Uncaught (in promise) TypeError: parent is undefined
[Detected 1 package: foundryvtt-mountup]
    isAncestor mountManager.js:610
    mountUpHud mountManager.js:40
    addMountButton mountHud.js:58
    jQuery 8
    addMountButton mountHud.js:57
    renderMountHud mountHud.js:31
    readyHooks module.js:66
    _call foundry.js:294
    call foundry.js:279
    _render foundry.js:3119
    _render foundry.js:52596
    render foundry.js:3023
    bind foundry.js:52571
    bind foundry.js:55058
    _onClickRight foundry.js:21910
    callback foundry.js:24202
    _handleClickRight foundry.js:24454
    _handleRightDown foundry.js:24434
    emit index.js:181
    dispatchEvent interaction.min.js:8
    processPointerDown interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    findHit interaction.min.js:8
    processInteractive interaction.min.js:8
    onPointerDown interaction.min.js:8

**Comment by p4535992** [comment]
I put a check for this exception on the last version. I'll close this issue, if the problem persist you can re-open this issue.
